name: InspireIlluminateLLC
favicon: null
layout_spectrum: 0.7251021186821163
typography_spectrum: 0.6815967638976872
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8e493'
    - '#7f589c'
    - '#83ae4e'
    - '#6b1567'
    - '#c382d3'
  brandStrength: 0.35460616229102015
  lightness: 0.6074712867848575
  saturation: 0.739305971423164
  rhythmicContrast: 0.8108305654022843
purpose: []
